behaviors:
  GridBrain:
    trainer_type: ppo
    max_steps: 4000000
    time_horizon: 64
    summary_freq: 10000
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 2.0e-4
      beta: 0.02
      epsilon: 0.2
    network_settings:
      num_layers: 2
      hidden_units: 128
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 2.0
    # behavioral_cloning:
    #   demo_path: "C:/Users/M S I/Desktop/GamePartI/FinalProject/Assets/Arc/SCRIPT/Trajectories/ComenPress.demo"
    #   strength: 0.2
    #   steps: 500000
    #   batch_size: 512          
    #   samples_per_update: 0